on:
  push:
    branches:
      - main
      - master

jobs:
  meu-job:
    runs-on: ubuntu-latest 

    steps:
      - run: echo "The job was automatically triggered by a event."
      - run: echo " This job is nowrunning on a server by GirHub!"
      
  segundo-job:
    runs-on: ubuntu-latest 

    steps: 
      - run : echo " Hoje é $(date)."
      - run : ls -la

      - uses: actions/checkout@v6

      - run : ls -la