name: "[AUTOMATICA] Minha primeira Action Bonita!!"

on:
  push:
    branches:
      - main
      - master

jobs:
  meu-job:
    runs-on: ubuntu-latest 

    steps:
      - name: Primeiro Step
        run: |
          echo "The job was automatically triggered by a event."
          echo "This job is nowrunning on a server by GirHub!"
      
  segundo-job:
    runs-on: ubuntu-latest 

    steps: 
      - name: Segundo Step
        run: |
          echo "Hoje é $(date)."
          ls -la

      - uses: actions/checkout@v6

      - run: ls -la